apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kaktooss.fullname" . }}-configreader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: [{{ template "kaktooss.name" . }}]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["watch"]