apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kaktooss.fullname" . }}-configreader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kaktooss.fullname" . }}-configreader
subjects:
- kind: ServiceAccount
  name: {{ template "kaktooss.fullname" . }}